theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

title: "SD Maid 1"
description: "An Android app that helps you manage files and apps."
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
  - CHANGELOG.md
exclude:
  - changelogV*
